plugins {
    id 'maven-publish'
}
allprojects {
    group = 'org.staircase'
    version = '3.1.2'
}

subprojects {
    apply plugin: 'java'

    sourceCompatibility = '21'
    targetCompatibility = '21'

    java {
        withSourcesJar()
    }

    tasks.withType(JavaCompile).configureEach {
        options.encoding = 'UTF-8'
    }

    tasks.withType(Test).configureEach {
        useJUnitPlatform()

        testLogging {
            events("passed", "skipped", "failed")
            showExceptions = true
        }
    }

    publishing {
        repositories {
            maven {
                name = "AwsCodeArtifact"
                url = "https://artifacts.staircase.ai/maven/staircase-ai-java/"
            }
        }
    }

}
